name: Build and Release

on:
  push:
    branches:
    - "main"

jobs:
# 1. build missRirica the vite project
# 2. build missRirica Android client
# 3. release debug APK
  build_missririca_client:
    name: Build missRirica
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.5.0]
    steps:        
      - name: Build MissRirica
        uses: actions/checkout@v3
        with:
          path: missRirica-client
      - name: Set Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: missRirica-client/node_modules
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-missRirica-client
      - name: Install Packages
        run: test -d ./missRirica-client/node_modules && echo "node_modules exists" || yarn install --frozen-lockfile --cwd='./missRirica-client'
      - name: Build
        run: cd missRirica-client && yarn build
      - name: Archive
        run:  tar -Jcf missRirica-client.tar.xz missRirica-client
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: missRirica-client
          path: missRirica-client.tar.xz
          retention-days: 1

  build_apk:
    name: Build missRirica
    needs: build_missririca_client
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java Env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Download missRirica-client
        uses: actions/download-artifact@v3
        with:
          name: missRirica-client
      - name: Extract missRirica-client
        run:  tar -Jxf missRirica-client.tar.xz
      - name: Build using Gradle with Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          save-generated-gradle-jars: false
          arguments: build
          remote-build-cache-proxy-enabled: false
          build-root-directory: missRirica-client/android
          save-local-build-cache: false
          concurrent: true
          gradle-build-scan-report: false
          gradle-distribution-sha-256-sum-warning: false
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          automatic_release_tag: "latest"
          title: "Development Build"
          files: ./missRirica-client/android/app/build/outputs/apk/debug/app-debug.apk